### ISSUE TITLE
Revamp tokens and add import / export support

### ISSUE THREAD

**Issue by TIny-Hacker** [TIny-Hacker/language-ti-basic#4]
## Info
It would be a significant improvement to add import / export support to the extension, and no longer require the additional step of copying and pasting from SC3 or TI-Connect CE. Most likely would be done using [tivars_lib_cpp](https://github.com/adriweb/tivars_lib_cpp).

## Tasks
- [x] Research way to make the feature fit in well with VS Code - use command palette.
- [x] Change highlighting to match the token syntax [here](https://github.com/TI-Toolkit/tokens/blob/main/8X.xml) as opposed to SC3's
- [x] Import / export TI-BASIC programs

**Comment by TIny-Hacker** [comment]
Importing seems to work, but it's a little slow and could still be improved somewhat. I'll look into exporting next.

**Comment by TIny-Hacker** [comment]
Importing and exporting works properly now. However, I'm waiting to push till:
- [x] Correct indentation
- [x] Use tivars_lib_cpp with ASCII
- [x] Return certain unicode

**Comment by TIny-Hacker** [comment]
I still need to do some testing but otherwise the feature is good to go as of 97a7cabfcc4c3d39b4e527b579fe836f1634ac56.
